/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.DAOProvider;
import controller.NProvider;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.table.DefaultTableModel;

public class ViewProvider extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Cliente
     */
    BackPanel back = new BackPanel();

    public ViewProvider() {
        this.setContentPane(back);

        initComponents();
        this.setLocationRelativeTo(null);
        mostrar("");
        habilitar();

    }

    void mostrar(String BuscarDato) {

        try {

            DefaultTableModel modelo;
            NProvider f = new NProvider();

            modelo = f.consult(BuscarDato);

            // modelo = providerController.mostrar (BuscarDato);
            listado.setModel(modelo);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClientBackGround = new BackPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtidproveedor = new javax.swing.JLabel();
        txtidpersona = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");

        pnlClientBackGround.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientBackGround.setPreferredSize(new java.awt.Dimension(928, 523));
        pnlClientBackGround.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 35, 34));
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 35, 34));
        jLabel4.setText("Identificacion");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 35, 34));
        jLabel5.setText("Nombres");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 35, 34));
        jLabel6.setText("Apellidos");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 35, 34));
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 35, 34));
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 35, 34));
        jLabel9.setText("Direccion");

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.setGridColor(new java.awt.Color(153, 153, 153));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 35, 34));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgBusqueda.png"))); // NOI18N

        txtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaActionPerformed(evt);
            }
        });
        txtConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultaKeyReleased(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgNuevo.PNG"))); // NOI18N
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(0, 0, 0));
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgGuardar.PNG"))); // NOI18N
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 51, 0));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgEliminar.PNG"))); // NOI18N
        btneliminar.setBorderPainted(false);
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setBackground(new java.awt.Color(255, 255, 255));
        btneditar.setForeground(new java.awt.Color(51, 51, 51));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgEditar.PNG"))); // NOI18N
        btneditar.setBorderPainted(false);
        btneditar.setContentAreaFilled(false);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgSalir.PNG"))); // NOI18N
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setText("Tipo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Estado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Proveedores");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "VIGENTE", "INACTIVO" }));

        txtidproveedor.setForeground(new java.awt.Color(255, 255, 255));

        txtidpersona.setForeground(new java.awt.Color(255, 255, 255));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "NATURAL", "JURIDICA" }));

        javax.swing.GroupLayout pnlClientBackGroundLayout = new javax.swing.GroupLayout(pnlClientBackGround);
        pnlClientBackGround.setLayout(pnlClientBackGroundLayout);
        pnlClientBackGroundLayout.setHorizontalGroup(
            pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8)))))
                                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel1))
                                    .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(lblTipo)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addGap(31, 31, 31)
                                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(133, 133, 133)))
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(260, 260, 260)))
                        .addGap(34, 34, 34)))
                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1256, 1256, 1256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1276, 1276, 1276))
                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlClientBackGroundLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1211, 1211, 1211))))
        );
        pnlClientBackGroundLayout.setVerticalGroup(
            pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientBackGroundLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlClientBackGroundLayout.createSequentialGroup()
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(pnlClientBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlClientBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlClientBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed

        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la Identificacion ", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtCodigoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Codigo de Proveedor", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (cmbTipo.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione el Tipo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtNombres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Nombre", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el correo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (cmbEstado.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Especifique si el empleado se encuentra activo o inactivo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else {
            /*                EDITAR VALORES A LA TABLA CLIENTE                                              */
            DAOProvider provider = new DAOProvider();

            NProvider providerController = new NProvider();
            provider.setProviderID(Integer.parseInt(txtidproveedor.getText()));
            provider.setPersonID(Integer.parseInt(txtidpersona.getText()));
            provider.setProviderCode(txtCodigoProveedor.getText());
            provider.setDni(txtCedula.getText());
            provider.setType(cmbTipo.getSelectedItem().toString());
            provider.setName(txtNombres.getText());
            provider.setLastName(txtApellidos.getText());
            provider.setAddress(txtDireccion.getText());
            provider.setPhoneNumber(txtTelefono.getText());
            provider.setEmail(txtEmail.getText());
            if(cmbEstado.getSelectedItem().toString().equals("VIGENTE")){
                provider.setState("1");
            }else{
                provider.setState("0");
            }

            providerController.editProvider(provider);

            JOptionPane.showMessageDialog(this, "Los datos han sido modificados", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            mostrar("");
            limpiar();
            habilitar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (!txtCodigoProveedor.getText().equals("")) {

            int con = JOptionPane.showConfirmDialog(rootPane, "¿Desea Eliminar el Registro?");

            if (con == 0) {

                DAOProvider provider = new DAOProvider();
                NProvider providerController = new NProvider();

                provider.setProviderID(Integer.parseInt(txtidproveedor.getText()));

                providerController.deleteProvider(provider);

                JOptionPane.showMessageDialog(this, "Los datos han sido eliminados", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                mostrar("");

                limpiar();

                habilitar();

            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if (txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la Identificacion ", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtCodigoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Codigo de Proveedor", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (cmbTipo.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Seleccione el Tipo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtNombres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el Nombre", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el correo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (cmbEstado.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Especifique si el empleado se encuentra activo o inactivo", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else {

            DAOProvider provider = new DAOProvider();

            NProvider providerController = new NProvider();

            // provider.setIdcliente(Integer.parseInt(txtCodigo.getText()));
            provider.setProviderCode(txtCodigoProveedor.getText());
            provider.setDni(txtCedula.getText());
            provider.setType(cmbTipo.getSelectedItem().toString());
            provider.setName(txtNombres.getText());
            provider.setLastName(txtApellidos.getText());
            provider.setAddress(txtDireccion.getText());
            provider.setPhoneNumber(txtTelefono.getText());
            provider.setEmail(txtEmail.getText());
            if(cmbEstado.getSelectedItem().toString().equals("VIGENTE")){
                provider.setState("1");
            }else{
                provider.setState("0");
            }
            providerController.insertPerson(provider);
            providerController.insertProvider(provider);

            JOptionPane.showMessageDialog(this, "Los datos han sido guardados", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            mostrar("");
            limpiar();
            habilitar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        mostrar("");
        /*                  BORAR DATO DE LA CAJA DE TEXTOS                                             */

        limpiar();

        habilitar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaKeyReleased

        mostrar(txtConsulta.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaKeyReleased

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

        limpiar();

        int fila = listado.rowAtPoint(evt.getPoint());

        try {
            txtCodigoProveedor.setText(listado.getValueAt(fila, 0).toString());
        } catch (NullPointerException nullE) {
            txtCodigoProveedor.setText("NULL");
        }
        if(listado.getValueAt(fila, 1).toString().equals("NATURAL")){
            cmbTipo.setSelectedItem(String.valueOf("NATURAL"));
        }else{
            cmbTipo.setSelectedItem(String.valueOf("JURIDICA"));
        }
        try {
            txtNombres.setText(listado.getValueAt(fila, 2).toString());
        } catch (NullPointerException nullE) {
            txtNombres.setText("NULL");
        }
        try {
            txtApellidos.setText(listado.getValueAt(fila, 3).toString());
        } catch (NullPointerException nullE) {
            txtApellidos.setText("NULL");
        }
        try {
            txtTelefono.setText(listado.getValueAt(fila, 4).toString());
        } catch (NullPointerException nullE) {
            txtTelefono.setText("NULL");
        }
        try {
            txtEmail.setText(listado.getValueAt(fila, 5).toString());
        } catch (NullPointerException nullE) {
            txtEmail.setText("NULL");
        }
        try {
            txtDireccion.setText(listado.getValueAt(fila, 6).toString());
        } catch (NullPointerException nullE) {
            txtDireccion.setText("NULL");
        }
        if(listado.getValueAt(fila, 7).toString().equals("1")){
            cmbEstado.setSelectedItem(String.valueOf("VIGENTE"));
        }else{
            cmbEstado.setSelectedItem(String.valueOf("INACTIVO"));
        }
        try {
            txtCedula.setText(listado.getValueAt(fila, 8).toString());
        } catch (NullPointerException nullE) {
            txtCedula.setText("NULL");
        }
        try {
            txtidpersona.setText(listado.getValueAt(fila, 10).toString());
        } catch (NullPointerException nullE) {
            txtDireccion.setText("NULL");
        }
        try {
            txtidproveedor.setText(listado.getValueAt(fila, 9).toString());
        } catch (NullPointerException nullE) {
            txtDireccion.setText("NULL");
        }
        desahabilitar();

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped

        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped

        //char c = evt.getKeyChar();
        //if (c < '0' || c > '9') {
            //    evt.consume();
            //}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyTyped
    private void habilitar() {

        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btneliminar.setEnabled(false);

    }

    private void desahabilitar() {

        btnguardar.setEnabled(false);
        btneditar.setEnabled(true);
        btneliminar.setEnabled(true);
    }

    private void limpiar() {

        this.txtCodigoProveedor.setText("");
        this.txtNombres.setText("");
        this.txtApellidos.setText("");
        this.txtCedula.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.txtEmail.setText("");
        cmbTipo.setSelectedItem(String.valueOf("Seleccionar"));
        cmbEstado.setSelectedItem(String.valueOf("Seleccionar"));

    }

    class BackPanel extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/images/imgClienteBg.PNG")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProvider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable listado;
    private javax.swing.JPanel pnlClientBackGround;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoProveedor;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtidpersona;
    private javax.swing.JLabel txtidproveedor;
    // End of variables declaration//GEN-END:variables
}
