/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NEmployee;
import controller.NCompra;
import controller.NProduct;
import model.DAOcompras;
import model.connection;
import java.sql.CallableStatement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static view.ViewVentas.txtcantidad;
import static view.ViewVentas.txtimporte;
import static view.ViewVentas.txtprecio;

/**
 *
 * @author juan
 */
public class ViewCompras extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();

    Connection con;
    CallableStatement cst;
    ResultSet r;
    int selectedRow = 0;
    int filas = 0;
    int rowNumber = 0;
    DefaultTableModel model;

    /**
     * Creates new form Compras
     */
    public ViewCompras() {
        initComponents();

        this.setLocationRelativeTo(null);

        Calendar cal = Calendar.getInstance();
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String fecha = sdf.format(date);
        txtfecha.setText(fecha);
        btnAgregarProductoCompra.setEnabled(false);
        jButton1.setEnabled(false);
        txtcantidad.setEnabled(false);
        btnQuitarProductoCompra.setEnabled(false);
        limpiar();
        incrementar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetalle = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodempleado = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txttelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtimporte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnConsultaProducto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtdocumento = new javax.swing.JComboBox();
        txtid = new javax.swing.JTextField();
        txtserie = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        txtcantidad1 = new javax.swing.JTextField();
        txtcantidad2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnAgregarProductoCompra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnQuitarProductoCompra = new javax.swing.JButton();
        txtusu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orden de Compras");
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(250, 239, 215));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 650, 10));

        tbdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbdetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdetalle);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 580, 140));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(250, 239, 215));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 160, -1));

        jPanel1.setBackground(new java.awt.Color(190, 171, 129));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombres.setEditable(false);
        txtnombres.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 208, -1));

        txtapellidos.setEditable(false);
        txtapellidos.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 208, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Codigo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 44, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Telefono");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 52, -1));

        txtcodempleado.setEditable(false);
        txtcodempleado.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtcodempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 133, -1));

        btnConsultar.setBackground(new java.awt.Color(204, 0, 0));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAddOff.png"))); // NOI18N
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 13, 30, 30));

        txttelefono.setEditable(false);
        txttelefono.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 180, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombres");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 56, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellidos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 56, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 580, 100));

        jPanel2.setBackground(new java.awt.Color(190, 171, 129));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdescripcion.setEditable(false);
        txtdescripcion.setBackground(new java.awt.Color(250, 239, 215));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descripcion");

        txtcantidad.setBackground(new java.awt.Color(250, 239, 215));
        txtcantidad.setToolTipText("");
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        txtimporte.setEditable(false);
        txtimporte.setBackground(new java.awt.Color(250, 239, 215));
        txtimporte.setToolTipText("");
        txtimporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimporteActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Importe");

        txtprecio.setEditable(false);
        txtprecio.setBackground(new java.awt.Color(250, 239, 215));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Precio");

        txtcategoria.setEditable(false);
        txtcategoria.setBackground(new java.awt.Color(250, 239, 215));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Categoria");

        txtcodigo.setEditable(false);
        txtcodigo.setBackground(new java.awt.Color(250, 239, 215));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Codigo");

        btnConsultaProducto.setBackground(new java.awt.Color(204, 0, 0));
        btnConsultaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAddOff.png"))); // NOI18N
        btnConsultaProducto.setBorderPainted(false);
        btnConsultaProducto.setContentAreaFilled(false);
        btnConsultaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultaProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultaProductoMouseExited(evt);
            }
        });
        btnConsultaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConsultaProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 580, 130));

        jPanel4.setBackground(new java.awt.Color(190, 171, 129));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdocumento.setBackground(new java.awt.Color(250, 239, 215));
        txtdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Documento de Compra", " " }));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(250, 239, 215));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtserie.setEditable(false);
        txtserie.setBackground(new java.awt.Color(250, 239, 215));
        txtserie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtserie.setText("000");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("N°");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(2, 2, 2)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 270, 80));

        jPanel5.setBackground(new java.awt.Color(190, 171, 129));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Fecha");

        txtfecha.setEditable(false);
        txtfecha.setBackground(new java.awt.Color(250, 239, 215));
        txtfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 270, 30));

        txtcantidad1.setBackground(new java.awt.Color(250, 239, 215));
        txtcantidad1.setText("2");
        txtcantidad1.setToolTipText("");
        jPanel3.add(txtcantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 180, -1));

        txtcantidad2.setBackground(new java.awt.Color(250, 239, 215));
        txtcantidad2.setText("2");
        txtcantidad2.setToolTipText("");
        jPanel3.add(txtcantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 180, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Total");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 60, 20));

        jPanel6.setBackground(new java.awt.Color(190, 171, 129));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProductoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAgregar.png"))); // NOI18N
        btnAgregarProductoCompra.setBorderPainted(false);
        btnAgregarProductoCompra.setContentAreaFilled(false);
        btnAgregarProductoCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProductoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoCompraActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregarProductoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgGuardar.PNG"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgSalir.PNG"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 580, 50));

        btnQuitarProductoCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarProductoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgRemoveOff.png"))); // NOI18N
        btnQuitarProductoCompra.setText("Quitar Producto");
        btnQuitarProductoCompra.setBorderPainted(false);
        btnQuitarProductoCompra.setContentAreaFilled(false);
        btnQuitarProductoCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuitarProductoCompra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnQuitarProductoCompraMouseMoved(evt);
            }
        });
        btnQuitarProductoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuitarProductoCompraMouseExited(evt);
            }
        });
        btnQuitarProductoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoCompraActionPerformed(evt);
            }
        });
        jPanel3.add(btnQuitarProductoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 160, 40));

        txtusu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtusu.setForeground(new java.awt.Color(250, 239, 215));
        txtusu.setText("1");
        jPanel3.add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 70, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgLogoDelavegaMenu.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 280, 100));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgCloseOff.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaProductoActionPerformed

        txtprecio.setText("");
        txtcantidad.setText("");
        txtimporte.setText("");
        View_Consultar_Productos X = new View_Consultar_Productos();
        X.setVisible(true);

        txtcantidad.setEnabled(true);
        btnAgregarProductoCompra.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaProductoActionPerformed


    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        View_Consultar_Empleado X = new View_Consultar_Empleado();
        X.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed
    void incrementar() {

        //  NEGOCIO 
        NCompra auto = new NCompra();

        // VARIABLE  LLAMAR AL AUTOGENERAR VENTA   DE   NEGOCIO   NVENTA
        String d = auto.Autogenerar();

        //  codigo  variable  
        String codigo = auto.Autogenerar();
        //String es para poder autogenerar   0001  0002   pero como el tipo de dato tabla venta esta int 
        // por eso se come 000  y solo guardar  numero  1 

        // si el tipo de dato fuera char o varchar  hay si guardaria el cero 0001   0002
        // empieza nulo
        if (codigo == null) {

            // empieza del   0001  como referencia  puede ser otro p    x  etc
            txtid.setText("1");

        } else {

            // si ya exite un registro entonces sigue el siguiente  numero  2
            int increment = Integer.parseInt(codigo);

            increment = increment + 1;

            txtid.setText("" + increment);
        }

    }
    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased

        try {

//          double val1 = Double.parseDouble(txtcantidad.getText());
//        double val2 = Double.parseDouble(txtprecio.getText());
//         double suma = val1 * val2;
//
//        String valorTotal = Double.toString(suma);
//
//        txtimporte.setText(String.valueOf(valorTotal));
            String pr = txtprecio.getText();
            String can = txtcantidad.getText();

            double n2 = Double.parseDouble(pr);
            double n3 = Double.parseDouble(can);

            double re = n2 * n3;

            txtimporte.setText(String.valueOf(re));

        } catch (Exception e) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped

        //char c = evt.getKeyChar();
        //if (c < '0' || c > '9') {
        //    evt.consume();
        //}
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btnAgregarProductoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoCompraActionPerformed
        try {
            if (Double.parseDouble(txtcantidad.getText()) < 0.01) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
            } else {
                model = (DefaultTableModel) this.tbdetalle.getModel();

                model.addRow(new Object[filas]);

                for (int x = 0; x < this.tbdetalle.getColumnCount() - 1; x++) {

                    model.setValueAt(this.txtcodigo.getText(), filas, 0);
                    model.setValueAt(this.txtdescripcion.getText(), filas, 1);
                    model.setValueAt(this.txtprecio.getText(), filas, 2);
                    model.setValueAt(this.txtcantidad.getText(), filas, 3);
                    model.setValueAt(this.txtimporte.getText(), filas, 4);
                }

                filas++;

                ///////////////////
                txtTotal.setText("0");
                rowNumber = tbdetalle.getRowCount();

                int c = 0;

                do

        try {
                    int f = c++;

                    double n1 = Double.parseDouble(tbdetalle.getValueAt(f, 4).toString());
                    String nu = txtTotal.getText();
                    int nu2 = Integer.parseInt(nu);
                    double re = n1 + nu2;
                    txtTotal.setText(String.valueOf(re));

                    totales();

                } catch (Exception e) {
                } while (c < rowNumber);

                jButton1.setEnabled(true);
            }
        } catch (NumberFormatException nE) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
        }
    }//GEN-LAST:event_btnAgregarProductoCompraActionPerformed

    private void limpiar() {

        txtcodempleado.setText("");
        txtnombres.setText("");
        txttelefono.setText("");
        txtapellidos.setText("");
        txtcodigo.setText("");
        txtdescripcion.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
        txtimporte.setText("");
        txtTotal.setText("");
        DefaultTableModel modelo = (DefaultTableModel) tbdetalle.getModel();
        int mover = tbdetalle.getRowCount() - 1;
        int i;
        for (i = mover; i >= 0; i--) {
            modelo.removeRow(i);

        }
    }

    private void totales() {

        NProduct productController = new NProduct();
        String pre;
        String can;
        double iva = 0;
        double total = 0;
        double subtotal = 0;
        double precio;
        double cantidad;
        double imp = 0.0;
        String valorIva = productController.consultIva().substring(2, 4);

        for (int i = 0; i < tbdetalle.getRowCount(); i++) {
            pre = tbdetalle.getValueAt(i, 2).toString();
            can = tbdetalle.getValueAt(i, 3).toString();

            precio = Double.parseDouble(pre);
            cantidad = Double.parseDouble(can);

            imp = precio * cantidad;

            subtotal = subtotal + imp;
            //iva = subtotal * Double.parseDouble("0."+valorIva);
            //total = subtotal + iva;          

            tbdetalle.setValueAt(Math.rint(imp * 100) / 100, i, 4);

        }

        txtTotal.setText(Double.toString((double) Math.round(subtotal * 1000d) / 1000));
//        txtigv.setText(""+Math.rint(iva*100)/100);
//        txttotal.setText(""+Math.rint(total*100)/100);

    }

    void guardarDetalle() {

        DAOcompras v = new DAOcompras();

        NCompra f = new NCompra();

        for (int i = 0; i < tbdetalle.getRowCount(); i++) {

            int fa = Integer.parseInt(txtid.getText());

            String inventario = (tbdetalle.getValueAt(i, 0).toString());

            String cantidad = (tbdetalle.getValueAt(i, 3).toString());

            String precio = (tbdetalle.getValueAt(i, 2).toString());

            String totales = (tbdetalle.getValueAt(i, 4).toString());

            v.setCodigoCompra(fa);

            v.setInventario(inventario);

            v.setCantidad(cantidad);

            v.setValor_unitario(precio);

            v.setTotal(totales);

            f.detalle(v);
        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txtcodempleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado en el boton '+'", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los Datos", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los Datos", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else {

            //   CABECERA 
            DAOcompras v = new DAOcompras();

            NCompra f = new NCompra();

            v.setCodigoCompra(Integer.parseInt(txtid.getText()));

            v.setCodEmpleado(Integer.parseInt(txtcodempleado.getText()));

            v.setFecha(txtfecha.getText());

            v.setTotal(txtTotal.getText());

            f.insertar(v);

            /////****DETALLE******************************
            guardarDetalle();

            incrementar();
            limpiar();

            txtcantidad.setEnabled(false);

            btnAgregarProductoCompra.setEnabled(false);

            jButton1.setEnabled(false);

            dispose();

            ViewCompras X = new ViewCompras();
            X.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtimporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void tbdetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdetalleMouseClicked
        btnQuitarProductoCompra.setEnabled(true);
        selectedRow = tbdetalle.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tbdetalleMouseClicked

    private void btnQuitarProductoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoCompraActionPerformed
        model = (DefaultTableModel) this.tbdetalle.getModel();
        model.removeRow(selectedRow);
        rowNumber = tbdetalle.getRowCount();
        filas--;
        totales();
    }//GEN-LAST:event_btnQuitarProductoCompraActionPerformed

    private void btnQuitarProductoCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarProductoCompraMouseExited
        if (btnQuitarProductoCompra.isEnabled()) {
            Icon image = new ImageIcon("src/Images/imgRemoveOff.png");
            btnQuitarProductoCompra.setIcon(image);
        }
    }//GEN-LAST:event_btnQuitarProductoCompraMouseExited

    private void btnQuitarProductoCompraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarProductoCompraMouseMoved
        if (btnQuitarProductoCompra.isEnabled()) {
            Icon image = new ImageIcon("src/Images/imgRemoveOn.png");
            btnQuitarProductoCompra.setIcon(image);
        }
    }//GEN-LAST:event_btnQuitarProductoCompraMouseMoved

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon image = new ImageIcon("src/Images/imgCloseOn.png");
        btnClose.setIcon(image);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon image = new ImageIcon("src/Images/imgCloseOff.png");
        btnClose.setIcon(image);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        Icon image = new ImageIcon("src/Images/imgAddOff.png");
        btnConsultar.setIcon(image);
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseEntered
        Icon image = new ImageIcon("src/Images/imgAddOn.png");
        btnConsultar.setIcon(image);
    }//GEN-LAST:event_btnConsultarMouseEntered

    private void btnConsultaProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaProductoMouseExited
        Icon image = new ImageIcon("src/Images/imgAddOff.png");
        btnConsultaProducto.setIcon(image);
    }//GEN-LAST:event_btnConsultaProductoMouseExited

    private void btnConsultaProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaProductoMouseEntered
        Icon image = new ImageIcon("src/Images/imgAddOn.png");
        btnConsultaProducto.setIcon(image);
    }//GEN-LAST:event_btnConsultaProductoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoCompra;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConsultaProducto;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnQuitarProductoCompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable tbdetalle;
    public static javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtapellidos;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcantidad1;
    public static javax.swing.JTextField txtcantidad2;
    public static javax.swing.JTextField txtcategoria;
    public static javax.swing.JTextField txtcodempleado;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdescripcion;
    private javax.swing.JComboBox txtdocumento;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtimporte;
    public static javax.swing.JTextField txtnombres;
    public static javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtserie;
    public static javax.swing.JTextField txttelefono;
    private javax.swing.JLabel txtusu;
    // End of variables declaration//GEN-END:variables
}
