/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.connection;
import controller.NEmployee;
import controller.NProduct;
import controller.NVenta;
import model.DAOVentas;
import model.connection;
import java.sql.CallableStatement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import java.sql.*;
import java.util.logging.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author juan
 */
public class ViewVentas extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();

    Connection con;
    CallableStatement cst;
    ResultSet r;
    int selectedRow = 0;
    int filas = 0;
    int rowNumber = 0;

    DefaultTableModel model;

    /**
     * Creates new form Compras
     */
    public ViewVentas() {
        initComponents();

        this.setLocationRelativeTo(null);

        Calendar cal = Calendar.getInstance();

        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");

        String fecha = sdf.format(date);
        txtfecha.setText(fecha);

        btnAgregarProductoVenta.setEnabled(false);
        btnQuitarProductoVentas.setEnabled(false);
        jButton1.setEnabled(false);
        txtcantidad.setEnabled(false);
        limpiar();
        incrementar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdetalle = new javax.swing.JTable();
        txtsubtotal = new javax.swing.JTextField();
        btnconsultarproducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txtpago = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnpago = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtimporte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtserie = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnAgregarProductoVenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtcodpago = new javax.swing.JLabel();
        btnQuitarProductoVentas = new javax.swing.JToggleButton();
        txtusu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblCantidadVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generar Ventas");
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(250, 239, 215));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 660, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("IVA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 70, 20));

        tbdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbdetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdetalle);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 570, 140));

        txtsubtotal.setEditable(false);
        txtsubtotal.setBackground(new java.awt.Color(250, 239, 215));
        jPanel3.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 100, -1));

        btnconsultarproducto.setBackground(new java.awt.Color(204, 0, 0));
        btnconsultarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAddOff.png"))); // NOI18N
        btnconsultarproducto.setBorderPainted(false);
        btnconsultarproducto.setContentAreaFilled(false);
        btnconsultarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconsultarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconsultarproductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconsultarproductoMouseExited(evt);
            }
        });
        btnconsultarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarproductoActionPerformed(evt);
            }
        });
        jPanel3.add(btnconsultarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 30, 30));

        jPanel1.setBackground(new java.awt.Color(190, 171, 129));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombres.setEditable(false);
        txtnombres.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 21, 208, -1));

        txtapellidos.setEditable(false);
        txtapellidos.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 50, 208, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Codigo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 24, 53, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tipo Pago");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 53, -1, -1));

        txtcodcliente.setEditable(false);
        txtcodcliente.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtcodcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 21, 134, -1));

        btnConsultar.setBackground(new java.awt.Color(204, 0, 0));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAddOff.png"))); // NOI18N
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 16, 30, 30));

        txtpago.setEditable(false);
        txtpago.setBackground(new java.awt.Color(250, 239, 215));
        jPanel1.add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 50, 134, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombres");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 24, 56, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellidos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 53, 56, -1));

        btnpago.setBackground(new java.awt.Color(204, 0, 0));
        btnpago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAddOff.png"))); // NOI18N
        btnpago.setBorderPainted(false);
        btnpago.setContentAreaFilled(false);
        btnpago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpagoMouseExited(evt);
            }
        });
        btnpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 50, 30, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 570, 90));

        jPanel2.setBackground(new java.awt.Color(190, 171, 129));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtdescripcion.setEditable(false);
        txtdescripcion.setBackground(new java.awt.Color(250, 239, 215));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Descripcion");

        txtcantidad.setBackground(new java.awt.Color(250, 239, 215));
        txtcantidad.setToolTipText("");
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        txtimporte.setEditable(false);
        txtimporte.setBackground(new java.awt.Color(250, 239, 215));
        txtimporte.setToolTipText("");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Importe");

        txtprecio.setEditable(false);
        txtprecio.setBackground(new java.awt.Color(250, 239, 215));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio");

        txtcategoria.setEditable(false);
        txtcategoria.setBackground(new java.awt.Color(250, 239, 215));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Categoria");

        txtcodigo.setEditable(false);
        txtcodigo.setBackground(new java.awt.Color(250, 239, 215));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 570, 110));

        jPanel4.setBackground(new java.awt.Color(190, 171, 129));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtserie.setEditable(false);
        txtserie.setBackground(new java.awt.Color(250, 239, 215));
        txtserie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtserie.setText("000");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(250, 239, 215));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Documento de Venta", " " }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("N°");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(2, 2, 2)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 24, 260, 80));

        jPanel5.setBackground(new java.awt.Color(190, 171, 129));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Fecha");

        txtfecha.setEditable(false);
        txtfecha.setBackground(new java.awt.Color(250, 239, 215));
        txtfecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 260, 30));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(250, 239, 215));
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Sub Total");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 60, 20));

        txtIva.setEditable(false);
        txtIva.setBackground(new java.awt.Color(250, 239, 215));
        jPanel3.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 100, -1));

        jPanel6.setBackground(new java.awt.Color(190, 171, 129));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarProductoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgAgregar.png"))); // NOI18N
        btnAgregarProductoVenta.setBorderPainted(false);
        btnAgregarProductoVenta.setContentAreaFilled(false);
        btnAgregarProductoVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoVentaActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregarProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 92, 32));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgGuardar.PNG"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 94, 33));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgSalir.PNG"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 95, 29));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 570, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 50, 20));

        txtcodpago.setBackground(new java.awt.Color(255, 255, 255));
        txtcodpago.setForeground(new java.awt.Color(250, 239, 215));
        jPanel3.add(txtcodpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 30));

        btnQuitarProductoVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarProductoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgRemoveOff.png"))); // NOI18N
        btnQuitarProductoVentas.setText("Quitar Producto");
        btnQuitarProductoVentas.setBorderPainted(false);
        btnQuitarProductoVentas.setContentAreaFilled(false);
        btnQuitarProductoVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuitarProductoVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuitarProductoVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuitarProductoVentasMouseExited(evt);
            }
        });
        btnQuitarProductoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoVentasActionPerformed(evt);
            }
        });
        jPanel3.add(btnQuitarProductoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 160, 40));

        txtusu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtusu.setForeground(new java.awt.Color(153, 204, 255));
        txtusu.setText("1");
        jPanel3.add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 70, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgLogoDelavegaMenu.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 280, 100));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgCloseOff.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, -1));

        lblCantidadVenta.setForeground(new java.awt.Color(250, 239, 215));
        jPanel3.add(lblCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarproductoActionPerformed

        txtprecio.setText("");
        txtcantidad.setText("");
        txtimporte.setText("");
        View_Consultar_Productos_Ventas X = new View_Consultar_Productos_Ventas();
        X.setVisible(true);

        txtcantidad.setEnabled(true);

        btnAgregarProductoVenta.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultarproductoActionPerformed


    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        View_Consultar_Clientes X = new View_Consultar_Clientes();
        X.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased

        //  double val1 = Double.parseDouble(txtcantidad.getText());
        //double val2 = Double.parseDouble(txtprecio.getText());
        //double suma = val1 * val2;
        //String valorTotal = Double.toString(suma);
        //txtimporte.setText(valorTotal);
        String pr = txtprecio.getText();
        String can = txtcantidad.getText();

        double n2 = Double.parseDouble(pr);
        double n3 = Double.parseDouble(can);

        double re = n2 * n3;

        txtimporte.setText(String.valueOf(re));

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped

        String c = String.valueOf(evt.getKeyChar());
        if (c.matches(".*[0-9].*")) {

        } else if (c.contains(".")) {

        } else {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btnAgregarProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoVentaActionPerformed

        try {
            if (Double.parseDouble(txtcantidad.getText()) < 0.01) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
            } else if (Double.parseDouble(txtcantidad.getText()) > Double.parseDouble(lblCantidadVenta.getText())) {
                 JOptionPane.showMessageDialog(this, "Cantidad mayor a la disponible en inventario", "Cantidad Invalida", JOptionPane.ERROR_MESSAGE);
            } else {
                model = (DefaultTableModel) this.tbdetalle.getModel();

                model.addRow(new Object[filas]);

                for (int x = 0; x < this.tbdetalle.getColumnCount() - 1; x++) {

                    model.setValueAt(this.txtcodigo.getText(), filas, 0);
                    model.setValueAt(this.txtdescripcion.getText(), filas, 1);
                    model.setValueAt(this.txtprecio.getText(), filas, 2);
                    model.setValueAt(this.txtcantidad.getText(), filas, 3);
                    model.setValueAt(this.txtimporte.getText(), filas, 4);
                }

                filas++;

                ///////////////////
                txtsubtotal.setText("0");
                rowNumber = tbdetalle.getRowCount();

                int c = 0;

                do

        try {
                    int f = c++;

                    double n1 = Double.parseDouble(tbdetalle.getValueAt(f, 4).toString());
                    String nu = txtsubtotal.getText();
                    int nu2 = Integer.parseInt(nu);
                    double re = n1 + nu2;
                    txtsubtotal.setText(String.valueOf(re));

                    totales();

                } catch (Exception e) {
                } while (c < rowNumber);

                jButton1.setEnabled(true);
            }
        } catch (NumberFormatException nE) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad valida");
        }

        //}

    }//GEN-LAST:event_btnAgregarProductoVentaActionPerformed

    private void limpiar() {

        txtcodcliente.setText("");
        txtnombres.setText("");
        txtpago.setText("");
        txtapellidos.setText("");
        txtcodigo.setText("");
        txtdescripcion.setText("");
        txtprecio.setText("");
        txtcantidad.setText("");
        txtimporte.setText("");
        txtsubtotal.setText("");

        DefaultTableModel modelo = (DefaultTableModel) tbdetalle.getModel();
        int mover = tbdetalle.getRowCount() - 1;
        int i;
        for (i = mover; i >= 0; i--) {
            modelo.removeRow(i);

        }
    }

    private void totales() {

        NProduct productController = new NProduct();
        String pre;
        String can;
        double iva = 0;
        double total = 0;
        double subtotal = 0;
        double precio;
        double cantidad;
        double imp = 0.0;
        String valorIva = productController.consultIva().substring(2, 4);

        for (int i = 0; i < tbdetalle.getRowCount(); i++) {
            pre = tbdetalle.getValueAt(i, 2).toString();
            can = tbdetalle.getValueAt(i, 3).toString();

            precio = Double.parseDouble(pre);
            cantidad = Double.parseDouble(can);

            imp = precio * cantidad;

            subtotal = subtotal + imp;
            iva = subtotal * Double.parseDouble("0." + valorIva);
            System.out.println(iva);
            total = subtotal + iva;

            tbdetalle.setValueAt(Math.rint(imp * 100) / 100, i, 4);

        }

        txtsubtotal.setText(Double.toString((double) Math.round(subtotal * 1000d) / 1000));
        txtIva.setText("" + Math.rint(iva * 100) / 100);
        txttotal.setText("" + Math.rint(total * 100) / 100);

    }

    void incrementar() {

        //  NEGOCIO 
        NVenta auto = new NVenta();

        // VARIABLE  LLAMAR AL AUTOGENERAR VENTA   DE   NEGOCIO   NVENTA
        String d = auto.Autogenerar();

        //  codigo  variable  
        String codigo = auto.Autogenerar();
        //String es para poder autogenerar   0001  0002   pero como el tipo de dato tabla venta esta int 
        // por eso se come 000  y solo guardar  numero  1 

        // si el tipo de dato fuera char o varchar  hay si guardaria el cero 0001   0002
        // empieza nulo
        if (codigo == null) {

            // empieza del   0001  como referencia  puede ser otro p    x  etc
            txtid.setText("1");

        } else {

            // si ya exite un registro entonces sigue el siguiente  numero  2
            int increment = Integer.parseInt(codigo);

            increment = increment + 1;

            txtid.setText("" + increment);
        }

    }

    void guardarDetalle() {

        DAOVentas v = new DAOVentas();

        NVenta f = new NVenta();

        for (int i = 0; i < tbdetalle.getRowCount(); i++) {

            int fa = Integer.parseInt(txtid.getText());

            String inventario = (tbdetalle.getValueAt(i, 0).toString());

            String cantidad = (tbdetalle.getValueAt(i, 3).toString());

            String precio = (tbdetalle.getValueAt(i, 2).toString());

            String totales = (tbdetalle.getValueAt(i, 4).toString());

            v.setCodigoVenta(fa);

            v.setInventario(inventario);

            v.setCantidad(cantidad);

            v.setValor_unitario(precio);

            v.setTotal(totales);

            f.detalle(v);
        }

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txtcodcliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente en el boton '+' ", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtsubtotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los Datos", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else if (txtcodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los Datos", "Aviso", JOptionPane.ERROR_MESSAGE);

        } else {

            //   CABECERA 
            DAOVentas v = new DAOVentas();

            NVenta f = new NVenta();

            v.setCodigoVenta(Integer.parseInt(txtid.getText()));

            v.setNumero(txtcodcliente.getText());

            v.setFecha(txtfecha.getText());

            v.setSubTotal(txtsubtotal.getText());

            v.setIva(txtIva.getText());

            v.setTotal(txttotal.getText());

            v.setPago(txtcodpago.getText());

            f.insertar(v);

            /////****DETALLE******************************
            guardarDetalle();

            incrementar();

            limpiar();

            txtcantidad.setEnabled(false);

            btnAgregarProductoVenta.setEnabled(false);

            jButton1.setEnabled(false);

            dispose();

            ViewVentas X = new ViewVentas();
            X.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagoActionPerformed

        ViewConsulta_Pago X = new ViewConsulta_Pago();
        X.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnpagoActionPerformed

    private void btnQuitarProductoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoVentasActionPerformed
        model = (DefaultTableModel) this.tbdetalle.getModel();
        model.removeRow(selectedRow);
        rowNumber = tbdetalle.getRowCount();
        filas--;
        totales();
    }//GEN-LAST:event_btnQuitarProductoVentasActionPerformed

    private void tbdetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdetalleMouseClicked
        btnQuitarProductoVentas.setEnabled(true);
        selectedRow = tbdetalle.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tbdetalleMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        Icon image = new ImageIcon("src/Images/imgCloseOn.png");
        btnClose.setIcon(image);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        Icon image = new ImageIcon("src/Images/imgCloseOff.png");
        btnClose.setIcon(image);
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnQuitarProductoVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarProductoVentasMouseExited
        if (btnQuitarProductoVentas.isEnabled()) {
            Icon image = new ImageIcon("src/Images/imgRemoveOff.png");
            btnQuitarProductoVentas.setIcon(image);
        }
    }//GEN-LAST:event_btnQuitarProductoVentasMouseExited

    private void btnQuitarProductoVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarProductoVentasMouseEntered
        if (btnQuitarProductoVentas.isEnabled()) {
            Icon image = new ImageIcon("src/Images/imgRemoveOn.png");
            btnQuitarProductoVentas.setIcon(image);
        }
    }//GEN-LAST:event_btnQuitarProductoVentasMouseEntered

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        Icon image = new ImageIcon("src/Images/imgAddOff.png");
        btnConsultar.setIcon(image);
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseEntered
        Icon image = new ImageIcon("src/Images/imgAddOn.png");
        btnConsultar.setIcon(image);
    }//GEN-LAST:event_btnConsultarMouseEntered

    private void btnpagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpagoMouseExited
        Icon image = new ImageIcon("src/Images/imgAddOff.png");
        btnpago.setIcon(image);
    }//GEN-LAST:event_btnpagoMouseExited

    private void btnpagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpagoMouseEntered
        Icon image = new ImageIcon("src/Images/imgAddOn.png");
        btnpago.setIcon(image);
    }//GEN-LAST:event_btnpagoMouseEntered

    private void btnconsultarproductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultarproductoMouseExited
        Icon image = new ImageIcon("src/Images/imgAddOff.png");
        btnconsultarproducto.setIcon(image);
    }//GEN-LAST:event_btnconsultarproductoMouseExited

    private void btnconsultarproductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconsultarproductoMouseEntered
        Icon image = new ImageIcon("src/Images/imgAddOn.png");
        btnconsultarproducto.setIcon(image);
    }//GEN-LAST:event_btnconsultarproductoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProductoVenta;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JToggleButton btnQuitarProductoVentas;
    private javax.swing.JButton btnconsultarproducto;
    private javax.swing.JButton btnpago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblCantidadVenta;
    public static javax.swing.JTable tbdetalle;
    public static javax.swing.JTextField txtIva;
    public static javax.swing.JTextField txtapellidos;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcategoria;
    public static javax.swing.JTextField txtcodcliente;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JLabel txtcodpago;
    public static javax.swing.JTextField txtdescripcion;
    private javax.swing.JComboBox txtdocumento;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtimporte;
    public static javax.swing.JTextField txtnombres;
    public static javax.swing.JTextField txtpago;
    public static javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtserie;
    public static javax.swing.JTextField txtsubtotal;
    public static javax.swing.JTextField txttotal;
    private javax.swing.JLabel txtusu;
    // End of variables declaration//GEN-END:variables
}
